version: '3.9'

services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:latest
    working_dir: "/infra"
    environment:
      - AWS_REGION=ap-south-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${PWD}:/infra/